development:
  adapter: postgresql
  database: development_insider_ai
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: test_insider_ai
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: production_insider_ai
  pool: 5
  timeout: 5000
  host: localhost
